name = "PkgExample"
uuid = "e1aa9a4a-0013-4482-90d5-222538dc91f5"
authors = ["meudnaes <eliasudnes@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
